### ISSUE TITLE
RPLH-Vanilla Weird Action Issue

### ISSUE THREAD

**Issue by KevinBian107** [KevinBian107/RPLH#50]
RE empty extraction issue, please use the updated Re prompt that Jack fixed

Example:

----------EXECUTION AVAILABILITY CHECKER----------
JUDGE MODIFIED:
 {}
-------###-------###-------###-------LOCAL_ROW_0_COL_1-------###-------###-------###-------
-------###-------###-------###-------JUDGE_ON_ROW_0_COL_1-------###-------###-------###-------
Match response:{'0.5_0.5': ['target_blue', 'target_red', 'target_purple', 'target_purple', 'box_orange'], '0.5_1.5': ['box_red', 'target_green', 'box_purple', 'target_orange', 'box_blue'], '1.5_0.5': ['target_green', 'box_purple'], '1.5_1.5': ['box_purple', 'target_purple']}
Processed response:{}

----------EXECUTION AVAILABILITY CHECKER----------
JUDGE MODIFIED:
 {}
ORIGINAL PLAN:
 {}
-------###-------###-------###-------LOCAL_ROW_1_COL_0-------###-------###-------###-------
-------###-------###-------###-------JUDGE_ON_ROW_1_COL_0-------###-------###-------###-------
Match response:{'0.5_0.5': ['target_blue', 'target_red', 'target_purple', 'target_purple', 'box_orange'], '0.5_1.5': ['box_red', 'target_green', 'box_purple', 'target_orange', 'box_blue'], '1.5_0.5': ['target_green', 'box_purple'], '1.5_1.5': ['box_purple', 'target_purple']}
Processed response:{}

----------EXECUTION AVAILABILITY CHECKER----------
JUDGE MODIFIED:
 {}
-------###-------###-------###-------LOCAL_ROW_1_COL_1-------###-------###-------###-------
-------###-------###-------###-------JUDGE_ON_ROW_1_COL_1-------###-------###-------###-------
Match response:{'0.5_0.5': ['target_blue', 'target_red', 'target_purple', 'target_purple', 'box_orange'], '0.5_1.5': ['box_red', 'target_green', 'box_purple', 'target_orange', 'box_blue'], '1.5_0.5': ['target_green', 'box_purple'], '1.5_1.5': ['box_purple', 'target_purple']}
Processed response:{}

----------EXECUTION AVAILABILITY CHECKER----------
JUDGE MODIFIED:
 {}
ORIGINAL PLAN:
 {}

**Comment by KevinBian107** [comment]
Fixe agent passed in lcoation issue, this may be a issue coming from the environment representation?

**Comment by KevinBian107** [comment]
Match response:{
    "Agent[0.5, 0.5]": "move(box_red, target_red)",
    "Agent[0.5, 1.5]": null,
    "Agent[1.5, 0.5]": null,
    "Agent[1.5, 1.5]": null
}
Agent-action pair is inconsistent: {
    "Agent[0.5, 0.5]": "move(box_red, target_red)",
    "Agent[0.5, 1.5]": null,
    "Agent[1.5, 0.5]": null,
    "Agent[1.5, 1.5]": null
}
Processed response:{
    "Agent[0.5, 0.5]": "move(box_red, target_red)",
    "Agent[0.5, 1.5]": null,
    "Agent[1.5, 0.5]": null,
    "Agent[1.5, 1.5]": null
}


need to directly throw away no response agent stuff

**Comment by KevinBian107** [comment]
HISTORY METHOD: _w_no_history
Match response:{
    "action": "move(box_blue, square[1.5, 0.5])"
  }
Agent-action pair is inconsistent: {
    "action": "move(box_blue, square[1.5, 0.5])"
  }
Processed response:{
    "action": "move(box_blue, square[1.5, 0.5])"
  }

**Comment by KevinBian107** [comment]
----------RETAKE ACTION----------
Traceback (most recent call last):
  File "/Users/kevinb/Desktop/dsc190/RPLH/rplh_vanilla/rplh_inference.py", line 584, in <module>
    ) = run_exp(
  File "/Users/kevinb/Desktop/dsc190/RPLH/rplh_vanilla/rplh_inference.py", line 197, in run_exp
    response, token_num_count_list_add = with_action_syntactic_check_func(
  File "/Users/kevinb/Desktop/dsc190/RPLH/rplh_vanilla/execution_checker.py", line 271, in with_action_syntactic_check_func
    response, token_num_count_list_add = retake_action(
  File "/Users/kevinb/Desktop/dsc190/RPLH/rplh_vanilla/execution_checker.py", line 172, in retake_action
    retake_action_prompt_1 = prompt_func(feedback)
TypeError: rplh_prompt_func() got multiple values for argument 'state_update_prompt'
(rplh) (base) kevinb@Kevins-MacBook-Pro-2 RPLH %

**Comment by KevinBian107** [comment]
Fixed issue, wouldn't error out, but stuck in RETAKE ACTION while loop
