### ISSUE TITLE
RPLH-efficient Convergence Debug

### ISSUE THREAD

**Issue by KevinBian107** [KevinBian107/RPLH#56]

**Comment by KevinBian107** [comment]
Previously every new local agent does not take in the previous judges given by teh judge, this casuses an issue. Resolved this issue by passing judge respone into the respone dictionary:  data_local["response_list_dir"]

**Comment by KevinBian107** [comment]
Instead of saving aagin, directly use data_local["agent_dict"] = response but relapse inside the for loop

**Comment by KevinBian107** [comment]
Later ones one block keep gets moved around, not converging

**Comment by KevinBian107** [comment]
----------RETAKE ACTION----------
HISTORY METHOD: _w_markovian_state_action_history
LESS PROMPT IN MESSAGE CONSTRUCT
Length of messages 2
API call failed: 1 validation error for HCA
actions_plan
  Field required [type=missing, input_value={'attitude': ['A Good Dec..., position[0.5, 1.5])'}}, input_type=dict]
    For further information visit https://errors.pydantic.dev/2.9/v/missing
Traceback (most recent call last):
  File "/Users/kevinb/Desktop/dsc190/RPLH/rplh_efficient/rplh_inference.py", line 576, in <module>
    ) = run_exp(
  File "/Users/kevinb/Desktop/dsc190/RPLH/rplh_efficient/rplh_inference.py", line 198, in run_exp
    response, token_num_count_list_add = with_action_syntactic_check_func(
  File "/Users/kevinb/Desktop/dsc190/RPLH/rplh_efficient/execution_checker.py", line 204, in with_action_syntactic_check_func
    response, token_num_count_list_add = retake_action(
  File "/Users/kevinb/Desktop/dsc190/RPLH/rplh_efficient/execution_checker.py", line 142, in retake_action
    response = json.loads(raw_response)
  File "/Users/kevinb/miniforge3/envs/rplh/lib/python3.10/json/__init__.py", line 339, in loads
    raise TypeError(f'the JSON object must be str, bytes or bytearray, '
TypeError: the JSON object must be str, bytes or bytearray, not NoneType
(rplh) (base) kevinb@Kevins-MacBook-Pro-2 RPLH %
